# development environment for nibbly_kibble_logger
name: nibbly_kibble_logger
dependencies:
  - python=3
  - ipython
  - click=7.1
  - flask=1.1
  - pyyaml=5.3
  - pytest=5.4
  - pytest-cov=2.8
  - pylint=2.5

